name = "formulahub-api"
main = "worker.py"
compatibility_date = "2024-01-15"
compatibility_flags = ["python"]

[env.production]
name = "formulahub-api"

[env.staging]
name = "formulahub-api-staging"

[build]
command = "pip install -r requirements-cloudflare.txt"

[[env.production.vars]]
CURRENT_SEASON = "2025"
FASTF1_VERBOSE = "false"

[[env.staging.vars]]
CURRENT_SEASON = "2025"
FASTF1_VERBOSE = "false"

# Add routes for custom domain (optional)
# [[env.production.routes]]
# pattern = "api.formulahub.com/*"
# zone_name = "formulahub.com"
